export enum ValueEnum {
  TRUST = "TRUST",
  RESPECT = "RESPECT",
  TRANSPARENCY = "TRANSPARENCY",
  QUALITY = "QUALITY",
  ETHICS = "ETHICS",
  COLABORATION = "COLABORATION",
  RESPONSABILITY = "RESPONSABILITY",
  INNOVATION = "INNOVATION",
  GOURMET = "GOURMET",
  LAUNDRY = "LAUNDRY",
  DOUBLE_ARROWS = "DOUBLE_ARROWS",
  KITCHEN = "KITCHEN",
  METRICS = "METRICS",
  SUITES = "SUITES",
  BALCONY = "BALCONY",
  GARAGE = "GARAGE"
}

export type ValueProps = {
  label: string;
  icon: ValueEnum;
};
