name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Verify pnpm
        run: |
          # Install pnpm using corepack (most reliable method)
          sudo corepack enable
          corepack prepare pnpm@8.7.5 --activate

          # Alternative installation if corepack fails
          if ! command -v pnpm &> /dev/null; then
            echo "Corepack method failed, trying npm install..."
            sudo npm install -g pnpm@8.7.5
          fi

          # Verify installation
          echo "PNPM path: $(which pnpm)"
          echo "PNPM version: $(pnpm --version)"

          # Ensure pnpm is in PATH
          echo "$(which pnpm)" >> $GITHUB_PATH

      - name: Setup Project
        run: |
          # Force pnpm usage regardless of package.json
          pnpm install --ignore-scripts
          pnpm add -D @tailwindcss/postcss@latest tailwindcss@^3.0.0

          # Update PostCSS config
          echo "module.exports = { plugins: { '@tailwindcss/postcss': {}, autoprefixer: {} } }" > postcss.config.js

      - name: Run Tests
        run: |
          export NODE_ENV=test
          pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
