name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install pnpm
        run: |
          npm install -g pnpm@8.7.5
          echo "PNPM path: $(which pnpm)"
          echo "PNPM version: $(pnpm --version)"

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D @tailwindcss/postcss@latest tailwindcss@^3.0.0
          pnpm dlx npm-check-updates --upgrade --filter "/^@?tailwind/" --target greatest

      - name: Configure PostCSS
        run: |
          if [ -f postcss.config.js ]; then
            echo "Updating postcss.config.js"
            sed -i "s/require('tailwindcss')/require('@tailwindcss\/postcss')/g" postcss.config.js
          else
            echo "No postcss.config.js found, creating one"
            echo "module.exports = { plugins: { '@tailwindcss/postcss': {}, autoprefixer: {} } }" > postcss.config.js
          fi

      - name: Run tests
        run: |
          export NODE_ENV=test
          pnpm exec playwright test

      # 6. Upload report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
