name: Generate a build and push to another branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          # Install pnpm globally using npm
          sudo npm install -g pnpm@8.7.5

          # Verify installation
          echo "PNPM path: $(which pnpm)"
          echo "PNPM version: $(pnpm --version)"

          # Explicitly add to PATH (critical step)
          echo "$(which pnpm)" >> $GITHUB_PATH

          # Verify PATH contains pnpm
          echo "PATH: $PATH"

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D @tailwindcss/postcss@latest

      - name: Build
        run: pnpm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to build branch
        run: |
          git switch --orphan build
          git rm -rf .
          cp -r dist/* .
          git add -A
          git commit -m "Build: $(git rev-parse --short HEAD)"
          git push origin build --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
