name: Run Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.7.5
          run_install: false

      - uses: actions/cache@v3
        name: Cache pnpm
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup Node
        uses: actions/setup-node@v3
      - run: pnpm install
      - run: pnpm test
      - run: pnpm run build
