name: Run Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          sudo corepack enable
          corepack prepare pnpm@8.7.5 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D @tailwindcss/postcss@latest

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run build